### ISSUE TITLE
numpy component naming

### ISSUE THREAD

**Issue by rleigh-codelibre** [boostorg/python#121]
Hi,

I've been prepping the CMake support for 1.64, including numpy support: https://gitlab.kitware.com/rleigh/cmake/commits/boost-1.64-deps

While we have `python` and `python_mpi` components matching the corresponding `boost_python` and `boost_python_mpi` libraries, `numpy` isn't named `python_numpy` which is a little inconsistent with the existing naming.  Since we're going to be using this as a CMake package component name which has compatibility concerns, I wanted to double check if this was deliberate or an oversight, and what the rationale was?

Many thanks,
Roger

**Comment by stefanseefeld** [comment]
I think ideally I would have called the project Boost.Numpy, but that would require for it to be a separate project (requiring a formal review process etc., when it technically is just an extension to Boost.Python.)

But since the term "NumPy" already contains "Python", I found "boost_python_numpy" to be redundant, so I shortened it to "boost_numpy".

**Comment by rleigh-codelibre** [comment]
OK, thanks for the clarification.  I'll leave things as they are on the CMake side in this case, using `numpy` as the Boost sub-component name.
