### ISSUE TITLE
Appveyor appears to be broken.

### ISSUE THREAD

**Issue by garyfurnish** [boostorg/python#150]
It appears that the appveyor tests always fail.
It might be that even selecting a 2017 environment, scons is finding the wrong compiler so it is not testing with 2017 but is always testing with 2015. An upgrade to scons may be necessary.

**Comment by stefanseefeld** [comment]
I have switched from `SCons` to `Faber` for the CI build system (and will likely retire the SCons-based build system in the near future). The new infrastructure works much better. It notably doesn't fail just because individual tests fail. Now we can concentrate on Boost.Python test failures (which for the most part seem MSVC compiler limitations and bugs to work around).
