### ISSUE TITLE
cpp_ndarray.shape(-1) should behave like python_ndarray.shape[-1] and boost::python::tuple::operator[](-1)

### ISSUE THREAD

**Issue by mborgerding** [boostorg/python#157]
Currently `ndarray::shape(int n)` returns `get_shape()[n]`, which indexes a raw memory buffer (C-style array). This results in undefined behavior under the python idiom of negative indices.

I propose `shape` ( and similarly `strides`) performs bounds checking and indexing from the back for negatives.

**Comment by stefanseefeld** [comment]
That sounds reasonable. Care to submit a patch ? ;-)

**Comment by mborgerding** [comment]
There is a failed CI build, but I cannot see any resemblence to my changes.

`unresolved external symbol  ... boost::get_pointer<struct test_class<0> ...`

**Comment by stefanseefeld** [comment]
Right, I know. (The problem is that the build system I use is broken, too, as the whole test run fails rather than just flagging the failed test. I'm working on a new build system to supersede the SCons-based one.)
Don't worry about that. I'm just waiting for the Travis build to finish. Your patch looks good, and I'm looking forward to merging it once it's confirmed that the new tests pass and no regressions are introduced. Thanks !
